name: Update Lottery Data

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python scripts/getdata.py

      - name: Run analysis
        run: python scripts/analyze_duplicates.py

      - name: Commit updates
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/sgtoto.csv reports/checkduplicate.md
          git commit -m "Auto update data and analysis report" || echo "No changes to commit"
          git push
