name: Update data and publish page

on:
  push:
    branches: [ main ]          # or your default branch
    paths:
      - 'analyses/**'
      - 'scripts/**'
      - 'docs/**'
      - 'requirements.txt'
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write    # push back to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4

      - name: Fetch latest data
        run: python scripts/getdata.py

      - name: Build one-pager (docs/index.md)
        run: python scripts/buildpage.py

      - name: Commit & push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if ! git diff --quiet; then
            git add -A
            git commit -m "chore(pages): refresh one-pager"
            git push
          else
            echo "No changes."
          fi
